### ISSUE TITLE
Beginning code

### ISSUE THREAD

**Issue by babicold** [stellarpower/new_cast-Implementation#1]
I'm a beginner I need more hint to give me a good go ahead of 🏦

**Comment by stellarpower** [comment]
What is it you're looking for, sorry?

**Comment by babicold** [comment]
I’m a new beginner on git I need a mentorship I’m going to bring in more
business for us ?

**Comment by stellarpower** [comment]
This probably isn't the right repository for learning git then - maybe try [this page here](https://docs.github.com/en/get-started/quickstart/hello-world). Not sure how you came across it as I haven't touched this in ages, and I don't think anybody else has looked at recently, so would be interested how you ended up on this page :sweat_smile:

**Comment by babicold** [comment]
Thanks, I'll check it out.

**Comment by stellarpower** [comment]
You're welcome. Also I'd look for a git tutorial or something similar, but issues are used specifically for people's projects and managing those.
